"""
Django settings for bitacora project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from ldap3 import Server, Connection, ALL, NTLM

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qbssul14qj^y6#rd3lw0sz12+80yqavc@_7(4oy)-%tut^lf%e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['http://bitacora.corralport.com', 'https://bitacora.corralport.com']


LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'login'

# Seguridad de cabeceras
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Opcionales pero recomendables
X_CONTENT_TYPE_OPTIONS = 'nosniff'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# Application definition

INSTALLED_APPS = [
    'django_crontab',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'server.apps.ServerConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'dbbackup',
]


DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BASE_DIR / 'backup'}

CRONJOBS = [
    ('*/1 * * * *', 'server.cron.my_backup')
]


AUTHENTICATION_BACKENDS = (
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
    'server.auth_backends.LDAPBackend',  
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'bitacora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bitacora.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

LOGIN_URL = 'login'  


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'  

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.gmail.com'
EMAIL_PORT = 465  # Si 587 no funciona, prueba con 465 o 25
EMAIL_USE_SSL = True  # Asegúrate de que esté en True
EMAIL_HOST_USER = 'tic@corralport.com'  # Tu correo corporativo
EMAIL_HOST_PASSWORD = 'yqwz gqrw kidd jqxg'  # Tu contraseña o contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'katalinagatita7520@gmail.com'  # Dirección de envío predeterminada



JAZZMIN_SETTINGS = {
    # Títulos y encabezados
    "site_title": "portuaria corral",  # Título en la pestaña del navegador
    "site_header": "bitacora portuaria corral",  # Encabezado principal
    "welcome_sign": "Bienvenido al panel de administración de portuaria corral",  # Mensaje de bienvenida
    "site_brand": "Bitacora",  # Texto en el menú de navegación

    # Logos
    "site_logo": "image\logo.png",  # Ruta dentro del directorio estático
    "site_logo_classes": "img-circle",  # Clases CSS para estilizar el logo
    "site_logo_style": "width: 30px; height: 30px;",  # Tamaño ajustado
    "login_logo": "image\logo.png",  # Logo en la página de inicio de sesión
    "login_logo_dark": "image\logo.png",  # Logo en temas oscuros

    # Colores y temas
    "theme": "default",  # Tema por defecto
    "theme_custom": {
        "primary_color": "#3498db",  # Color principal
        "secondary_color": "#2ecc71",  # Color secundario
    },

    # Mostrar el UI Builder
    "show_ui_builder": True,  # Habilitar el UI Builder

    # Usar la base de datos para almacenar configuraciones
    "use_database": True,  # Permite almacenar configuraciones personalizadas en la base de datos

    # Archivos personalizados CSS y JS
    "custom_css": "static/css/custom_admin.css",  # CSS personalizado
    "custom_js": "static/js/custom_admin.js",  # JS personalizado

    # Internacionalización
    "language_switcher": True,  # Habilitar selector de idioma
    "supported_languages": ["es", "es"],  # Idiomas soportados
    "default_language": "es",  # Idioma por defecto

    # Notificaciones
    "show_notifications": True,  # Habilitar notificaciones
    "custom_notifications": [
        {"text": "No olvides actualizar el inventario de equipos.", "icon": "fas fa-bell", "url": "/admin/equipos"},
        {"text": "Se necesita aprobación de nuevas solicitudes de socios.", "icon": "fas fa-user-check", "url": "/admin/solicitudsocio"},
    ],

    # Menú superior
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Documentación", "url": "https://docs.djangoproject.com", "new_window": True},
        {"model": "auth.User"},
        {"app": "auth"},
    ],

    # Pie de página
    "copyright": "Portuaria Corral  © 2025",
    "version": "1.0.0",

    # Barra de búsqueda
    "search_model": "auth.User",
    "search_field": "username",

    # Formatos
    "changeform_format": "carousel",
    "changeform_format_overrides": {
        "auth.user": "horizontal_tabs",
    },


    # Accesibilidad
    "accessibility_features": {
        "high_contrast_mode": True,
        "text_resizing": True,
    },

    # Mejoras visuales
    "layout": {
        "sidebar_fixed": True,
        "navbar_fixed": True,
        "footer_fixed": False,
    },

    # Configuración avanzada para modelos
    "advanced_model_settings": {
        "auth.user": {
            "readonly_fields": ["last_login", "date_joined"],
            "exclude_fields": ["password"],
        }
    },

    # Personalización de permisos
    "permissions": {
        "auth.group": {"add": True, "change": True, "delete": False},
        "auth.user": {"add": True, "change": True, "delete": True},
    },


    # Modo oscuro
    "dark_mode_toggle": True,
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "solar",
    "dark_mode_theme": "superhero",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
