# Generated by Django 5.2.8 on 2025-12-05 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('modo_visita', models.CharField(choices=[('visita_cliente', 'Visita a Cliente'), ('reunion_externa', 'Reunión Externa'), ('capacitacion', 'Capacitación'), ('inspeccion', 'Inspección'), ('otro', 'Otro')], max_length=20)),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora Externa',
                'verbose_name_plural': 'Bitácoras Externas',
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('modo_visita', models.CharField(choices=[('reunion', 'Reunión'), ('entrevista', 'Entrevista'), ('tramite', 'Trámite'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=20)),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora Interna',
                'verbose_name_plural': 'Bitácoras Internas',
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
    ]
