# Generated by Django 5.2.8 on 2025-12-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraexterna',
            name='modo_visita',
            field=models.CharField(choices=[('sala_servidores', 'Sala de Servidores'), ('sala_comunicaciones', 'Sala de comunicaciones')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacorainterna',
            name='modo_visita',
            field=models.CharField(choices=[('sala_servidores', 'Sala de Servidores'), ('sala_comunicaciones', 'Sala de comunicaciones')], max_length=20),
        ),
    ]
