# Generated by Django 5.2.8 on 2025-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_bitacoraexterna_modo_visita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraexterna',
            name='modo_visita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraexterna',
            name='responsable',
            field=models.CharField(choices=[('jefe_informatica', 'Jefe de  Informatica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacoraexterna',
            name='ubicacion',
            field=models.CharField(choices=[('sala_servidores', 'Sala de Servidores'), ('sala_comunicaciones', 'Sala de comunicaciones')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacorainterna',
            name='modo_visita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacorainterna',
            name='responsable',
            field=models.CharField(choices=[('jefe_informatica', 'Jefe de  Informatica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacorainterna',
            name='ubicacion',
            field=models.CharField(choices=[('sala_servidores', 'Sala de Servidores'), ('sala_comunicaciones', 'Sala de comunicaciones')], max_length=20),
        ),
    ]
