# Generated by Django 4.2.17 on 2025-01-09 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('nombre_visitante', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$', 'El campo solo puede contener letras.')])),
                ('ubicacion', models.CharField(choices=[('Sala de servidores', 'Sala de servidores'), ('Comunicaciones', 'Comunicaciones')], max_length=255)),
                ('motivo_visita', models.TextField()),
                ('responsable', models.CharField(choices=[('Andres', 'Andres')], max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$', 'El campo solo puede contener letras.')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
