# Generated by Django 4.2.17 on 2025-01-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
