# Generated by Django 4.2.17 on 2025-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_bitacoraacceso_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
