# Generated by Django 4.2.17 on 2025-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_bitacoraacceso_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraacceso',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
