# Generated by Django 4.2.17 on 2025-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_bitacoraacceso_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='nombre_visitante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='responsable',
            field=models.CharField(choices=[('Andres', 'Andres')], max_length=255),
        ),
    ]
