# Generated by Django 4.2.17 on 2025-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_bitacoraacceso_nombre_visitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='motivo_visita',
            field=models.TextField(blank=True, null=True),
        ),
    ]
