# Generated by Django 4.2.17 on 2025-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_bitacoraacceso_motivo_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAcceso_EXTERNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('nombre_visitante', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(choices=[('Sala de servidores', 'Sala de servidores'), ('Comunicaciones', 'Comunicaciones')], max_length=255)),
                ('motivo_visita', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(choices=[('Andres', 'Andres')], max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('ticket', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
