# Generated by Django 4.2.17 on 2025-01-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_bitacoraacceso_externa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoraacceso_externa',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='bitacoraacceso_externa',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='bitacoraacceso_externa',
            name='rut',
        ),
    ]
