# Generated by Django 4.2.17 on 2025-01-14 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_remove_bitacoraacceso_externa_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso_externa',
            name='nombre_visitante',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso_externa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
