# Generated by Django 4.2.17 on 2025-01-30 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0011_responsable_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBitacoraAcceso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('nombre_visitante', models.CharField(max_length=255)),
                ('motivo_visita', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.CharField(blank=True, max_length=255, null=True)),
                ('externo', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='server.responsable')),
                ('ubicacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='server.ubicacion')),
            ],
            options={
                'verbose_name': 'historical bitacora acceso',
                'verbose_name_plural': 'historical bitacora accesos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='bitacoraacceso',
            name='sexo',
        ),
        migrations.AddField(
            model_name='bitacoraacceso',
            name='externo',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BitacoraAcceso_EXTERNA',
        ),
    ]
